/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import Dominio.usuario;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.DefaultListSelectionModel;

/**
 *
 * @author Judi
 */
public class FLobby extends javax.swing.JFrame {
 DefaultListModel modelo = new DefaultListModel();
 ArrayList<usuario> usuarios = new ArrayList();
    /**
     * Creates new form FLobbyHost
     */
    public FLobby() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jPanelJugador1 = new javax.swing.JPanel();
        Ljugador1 = new javax.swing.JLabel();
        Lcolor1 = new javax.swing.JLabel();
        jPanelJugador2 = new javax.swing.JPanel();
        Ljugador2 = new javax.swing.JLabel();
        Lcolor2 = new javax.swing.JLabel();
        jPanelJugador3 = new javax.swing.JPanel();
        Ljugador3 = new javax.swing.JLabel();
        Lcolor3 = new javax.swing.JLabel();
        jPanelJugador4 = new javax.swing.JPanel();
        Ljugador4 = new javax.swing.JLabel();
        Lcolor4 = new javax.swing.JLabel();
        jButtonInicar = new javax.swing.JButton();
        LFondo = new javax.swing.JLabel();
        LApuesta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Lobby");
        setMinimumSize(new java.awt.Dimension(600, 375));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setText("Lobby de Espera Jugadores");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 400, 50));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 600, 10));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 268, 600, -1));

        jPanelJugador1.setBackground(new java.awt.Color(204, 255, 255));
        jPanelJugador1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelJugador1.setLayout(null);

        Ljugador1.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        Ljugador1.setText("\"DISPONIBLE\"");
        jPanelJugador1.add(Ljugador1);
        Ljugador1.setBounds(10, 10, 110, 30);

        Lcolor1.setFont(new java.awt.Font("Arial Black", 1, 8)); // NOI18N
        Lcolor1.setText("\"DISPONIBLE\"");
        jPanelJugador1.add(Lcolor1);
        Lcolor1.setBounds(30, 30, 70, 30);

        jPanel1.add(jPanelJugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 130, 180));

        jPanelJugador2.setBackground(new java.awt.Color(204, 255, 255));
        jPanelJugador2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelJugador2.setLayout(null);

        Ljugador2.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        Ljugador2.setText("\"DISPONIBLE\"");
        jPanelJugador2.add(Ljugador2);
        Ljugador2.setBounds(10, 10, 110, 30);

        Lcolor2.setFont(new java.awt.Font("Arial Black", 1, 8)); // NOI18N
        Lcolor2.setText("\"DISPONIBLE\"");
        jPanelJugador2.add(Lcolor2);
        Lcolor2.setBounds(30, 30, 70, 30);

        jPanel1.add(jPanelJugador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 130, 180));

        jPanelJugador3.setBackground(new java.awt.Color(204, 255, 255));
        jPanelJugador3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelJugador3.setLayout(null);

        Ljugador3.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        Ljugador3.setText("\"DISPONIBLE\"");
        jPanelJugador3.add(Ljugador3);
        Ljugador3.setBounds(10, 10, 110, 30);

        Lcolor3.setFont(new java.awt.Font("Arial Black", 1, 8)); // NOI18N
        Lcolor3.setText("\"DISPONIBLE\"");
        jPanelJugador3.add(Lcolor3);
        Lcolor3.setBounds(30, 30, 70, 30);

        jPanel1.add(jPanelJugador3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 130, 180));

        jPanelJugador4.setBackground(new java.awt.Color(204, 255, 255));
        jPanelJugador4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelJugador4.setLayout(null);

        Ljugador4.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        Ljugador4.setText("\"DISPONIBLE\"");
        jPanelJugador4.add(Ljugador4);
        Ljugador4.setBounds(10, 10, 110, 30);

        Lcolor4.setFont(new java.awt.Font("Arial Black", 1, 8)); // NOI18N
        Lcolor4.setText("\"DISPONIBLE\"");
        jPanelJugador4.add(Lcolor4);
        Lcolor4.setBounds(30, 30, 70, 30);

        jPanel1.add(jPanelJugador4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, 130, 180));

        jButtonInicar.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jButtonInicar.setForeground(new java.awt.Color(0, 255, 0));
        jButtonInicar.setText("Iniciar");
        jButtonInicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInicarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonInicar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 110, 40));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 600, 370);

        LFondo.setText("jLabel2");
        getContentPane().add(LFondo);
        LFondo.setBounds(610, 120, 50, 40);

        LApuesta.setText("jLabel2");
        getContentPane().add(LApuesta);
        LApuesta.setBounds(610, 180, 41, 16);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonInicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInicarActionPerformed
        // TODO add your handling code here:
         /* Create and display the form */
         //Solo sera valido o el jugador creador podra iniciar
                
       
        usuario usuario = new usuario();
        usuario.setNombre(Ljugador1.getText());
        usuario.setColor(Lcolor1.getText());
        usuarios.add(usuario);
        
        usuario usuario2 = new usuario();
        usuario2.setNombre(Ljugador2.getText());
        usuario2.setColor(Lcolor2.getText());
        usuarios.add(usuario2);
        
        usuario usuario3 = new usuario();
        usuario3.setNombre(Ljugador3.getText());
        usuario3.setColor(Lcolor3.getText());
        usuarios.add(usuario3);
        
        usuario usuario4 = new usuario();
        usuario4.setNombre(Ljugador4.getText());
        usuario4.setColor(Lcolor4.getText());
        usuarios.add(usuario4);
        
         modelo.addElement(usuarios.get(0));
         modelo.addElement(usuarios.get(1));
         modelo.addElement(usuarios.get(2));
         modelo.addElement(usuarios.get(3));
         
         
         
         new FJuego().setVisible(true);
         FJuego.LNombreJugador.setText(Ljugador1.getText());
         
         FJuego.ListaJugadores.setModel(modelo); 
         FJuego.LMontoActual.setText(LFondo.getText());
         FJuego.LMontoActual1.setText(LFondo.getText());
         
         FJuego.LPena.setText(LApuesta.getText());
         FJuego.LPena1.setText(LApuesta.getText());
    }//GEN-LAST:event_jButtonInicarActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FLobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FLobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FLobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FLobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FLobby().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel LApuesta;
    public static javax.swing.JLabel LFondo;
    public static javax.swing.JLabel Lcolor1;
    public static javax.swing.JLabel Lcolor2;
    public static javax.swing.JLabel Lcolor3;
    public static javax.swing.JLabel Lcolor4;
    public static javax.swing.JLabel Ljugador1;
    public static javax.swing.JLabel Ljugador2;
    public static javax.swing.JLabel Ljugador3;
    public static javax.swing.JLabel Ljugador4;
    private javax.swing.JButton jButtonInicar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JPanel jPanelJugador1;
    public static javax.swing.JPanel jPanelJugador2;
    public static javax.swing.JPanel jPanelJugador3;
    public static javax.swing.JPanel jPanelJugador4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
