/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author Judi
 */
public class FLobby extends javax.swing.JFrame {

    /**
     * Creates new form FLobbyHost
     */
    public FLobby() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jPanelJugador1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanelJugador2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanelJugador3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanelJugador4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Lobby");
        setPreferredSize(new java.awt.Dimension(600, 375));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setText("Lobby de Espera Jugadores");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(110, 10, 400, 50);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(0, 80, 600, 10);
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(0, 268, 600, 2);

        jPanelJugador1.setBackground(new java.awt.Color(204, 255, 255));
        jPanelJugador1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelJugador1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel3.setText("Jugador 1");
        jPanelJugador1.add(jLabel3);
        jLabel3.setBounds(10, 10, 110, 30);

        jPanel1.add(jPanelJugador1);
        jPanelJugador1.setBounds(20, 80, 130, 180);

        jPanelJugador2.setBackground(new java.awt.Color(204, 255, 255));
        jPanelJugador2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelJugador2.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel4.setText("Jugador 2");
        jPanelJugador2.add(jLabel4);
        jLabel4.setBounds(10, 10, 110, 30);

        jPanel1.add(jPanelJugador2);
        jPanelJugador2.setBounds(160, 80, 130, 180);

        jPanelJugador3.setBackground(new java.awt.Color(204, 255, 255));
        jPanelJugador3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelJugador3.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel5.setText("Jugador 3");
        jPanelJugador3.add(jLabel5);
        jLabel5.setBounds(10, 10, 110, 30);

        jPanel1.add(jPanelJugador3);
        jPanelJugador3.setBounds(300, 80, 130, 180);

        jPanelJugador4.setBackground(new java.awt.Color(204, 255, 255));
        jPanelJugador4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelJugador4.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel2.setText("Jugador 4");
        jPanelJugador4.add(jLabel2);
        jLabel2.setBounds(10, 10, 110, 30);

        jPanel1.add(jPanelJugador4);
        jPanelJugador4.setBounds(440, 80, 130, 180);

        jButton1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 255, 0));
        jButton1.setText("Iniciar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(240, 280, 110, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 600, 370);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FLobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FLobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FLobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FLobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FLobby().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelJugador1;
    private javax.swing.JPanel jPanelJugador2;
    private javax.swing.JPanel jPanelJugador3;
    private javax.swing.JPanel jPanelJugador4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
