/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import Dominio.Jugador;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Carlos
 */
public class FUnirse extends javax.swing.JFrame {

    /**
     * Creates new form FUnirse2
     */
    public FUnirse() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButtonMenu = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        BoxColor = new javax.swing.JComboBox<>();
        jButtonUnirse = new javax.swing.JButton();
        txtnomjugador = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setText("Unirse a partida");

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel2.setText("Escoga su color;");

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel3.setText("Datos del jugador");

        jButtonMenu.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jButtonMenu.setForeground(new java.awt.Color(255, 0, 0));
        jButtonMenu.setText("Menu");
        jButtonMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenuActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel8.setText("Escriba su apodo;");

        BoxColor.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        BoxColor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Azul", "Amarillo", "Rojo", "Verde" }));

        jButtonUnirse.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jButtonUnirse.setForeground(new java.awt.Color(102, 255, 102));
        jButtonUnirse.setText("Unirse");
        jButtonUnirse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUnirseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(160, 160, 160)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jLabel3))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(txtnomjugador, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addComponent(BoxColor, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(280, 280, 280)
                            .addComponent(jButtonMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(130, 130, 130)
                            .addComponent(jButtonUnirse, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(20, 20, 20)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtnomjugador, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(20, 20, 20)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BoxColor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(30, 30, 30)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(8, 8, 8)
                            .addComponent(jButtonMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jButtonUnirse, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenuActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonMenuActionPerformed

    private void jButtonUnirseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUnirseActionPerformed
        // TODO add your handling code here:
        /* Create and display the form */
        
        if(validarCampos()==false){

            Jugador u = new Jugador();
            u.setNombre(txtnomjugador.getText());
            String color = (String) BoxColor.getSelectedItem();
            u.setColor(color);

            if (validarUsuarios(u)==false) {
                /*
                Codigo para asignar numeracion de jugadores temportal
                */

                if ( FLobby.Ljugador1.getText().equals("\"DISPONIBLE\"")) {
                    JOptionPane.showMessageDialog(null, "No hay un servidor disponible, favor de crear un servidor");
                    dispose();
//                    FLobby.Ljugador1.setText(u.getNombre());
//                    FLobby.Lcolor1.setText(u.getColor());
//                    FLobby.jPanelJugador1.setBackground(ValidarColor(color));

                }else if(FLobby.Ljugador2.getText().equalsIgnoreCase("\"DISPONIBLE\"")){
                    FLobby.Ljugador2.setText(u.getNombre());
                    FLobby.Lcolor2.setText(u.getColor());
                    FLobby.jPanelJugador2.setBackground(ValidarColor(color));

                }else if(FLobby.Ljugador3.getText().equalsIgnoreCase("\"DISPONIBLE\"")){
                    FLobby.Ljugador3.setText(u.getNombre());
                    FLobby.Lcolor3.setText(u.getColor());
                    FLobby.jPanelJugador3.setBackground(ValidarColor(color));

                }else if(FLobby.Ljugador4.getText().equalsIgnoreCase("\"DISPONIBLE\"")){
                    FLobby.Ljugador4.setText(u.getNombre());
                    FLobby.Lcolor4.setText(u.getColor());
                    FLobby.jPanelJugador4.setBackground(ValidarColor(color));
                    dispose();
                }
                /*
                Codigo para asignar numeracion de jugadores temportal
                */
            }

            /*
            temporal mente desactive el dispose, para que se puedan ir agregando diferentes jugadores,
            lo que pasa es que en la linea 16 se crea un frame configuracion_juego diferente
            por lo tando mientras no tengamos los metodos de conexion se mantrenda el dispose como comentado.
            */
//            
        }
    }//GEN-LAST:event_jButtonUnirseActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BoxColor;
    private javax.swing.JButton jButtonMenu;
    private javax.swing.JButton jButtonUnirse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField txtnomjugador;
    // End of variables declaration//GEN-END:variables
public boolean validarCampos() {
        if (txtnomjugador.getText().isEmpty() ) {
            JOptionPane.showMessageDialog(null, "Establece color y nombre de jugador para empezar");
        return true;
        }
        return false;
    }
    
    
    public boolean validarUsuarios(Jugador u) {
        try{
        if (u.getNombre().equals(FLobby.Ljugador1.getText()) ) {
            JOptionPane.showMessageDialog(null, "Nombre ya creado, favor de usar otro");
        return true;
        }
        if (u.getNombre().equals(FLobby.Ljugador2.getText()) ) {
            JOptionPane.showMessageDialog(null, "Nombre ya creado, favor de usar otro");
        return true;
        }
        if (u.getNombre().equals(FLobby.Ljugador3.getText()) ) {
            JOptionPane.showMessageDialog(null, "Nombre ya creado, favor de usar otro");
        return true;
        }
        if (u.getNombre().equals(FLobby.Ljugador4.getText())) {
            JOptionPane.showMessageDialog(null, "Nombre ya creado, favor de usar otro");
        return true;
        }
        
        if (u.getColor().equals(FLobby.Lcolor1.getText())) {
          
            JOptionPane.showMessageDialog(null, "Color ocupado, favor de seleccionar otro");
        return true;
        }
        if (u.getColor().equals(FLobby.Lcolor2.getText())) {
            JOptionPane.showMessageDialog(null, "Color ocupado, favor de seleccionar otro");
        return true;
        }
        if (u.getColor().equals(FLobby.Lcolor3.getText())) {
            JOptionPane.showMessageDialog(null, "Color ocupado, favor de seleccionar otro");
        return true;
        }
        if (u.getColor().equals(FLobby.Lcolor4.getText())) {
            JOptionPane.showMessageDialog(null, "Color ocupado, favor de seleccionar otro");
        return true;
        }
        }catch(NullPointerException e){
        JOptionPane.showMessageDialog(null, "No hay un servidor disponible, favor de crear un servidor");
                    dispose();
        } 
        
        
        return false;
    }
public Color ValidarColor(String color){
                    switch (color) {
                            case "Azul":
                                return Color.BLUE;
                            case "Amarillo":
                                return Color.YELLOW;
                            case "Rojo":
                                return Color.RED;
                            case "Verde":
                                return Color.GREEN;
                            }
    return Color.WHITE;
    
}

}
